### ISSUE TITLE
Bug: %raw name of item% not a single object

### ISSUE THREAD

**Issue by jaylawl** [SkriptLang/Skript#1473]
Skript dev 37 c
Spigot 1.12.1
```
command /test:
    trigger:
        
        set {_i} to diamond sword
        set {_raw} to raw name of {_i}
        send "%{_raw}%"
```

Parse error: `{_raw} can only be set to one object, not more`

Setting `{_raw::*} to raw name of %item%` works

**Comment by TheLimeGlass** [comment]
ItemTypes may have multiple aliases assigned to them, not so much a bug.

An advancement could be checking if the ItemType only has one aliases assigned to it.

#NewAliasesSystem

**Comment by Blueyescat** [comment]
Aliases? This returns Minecraft ID of an item. Can be fixed by adding a few characters to the code but it uses a unreliable and hacky way because Skript doesn't want NMS so i don't wanted to touch it.

**Comment by TheLimeGlass** [comment]
Aliases are ItemTypes

**Comment by Blueyescat** [comment]
The fix is 
https://github.com/SkriptLang/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprRawName.java#L84-L87
```diff
    @Override
    public boolean isSingle() {
-        return false;
+        return items.isSingle();
    }
```

**Comment by Blueyescat** [comment]
We discussed this in Discord and the result is that can't be fixed, because when you do `raw name diamond armor` it will return raw names of all diamond armors, plurality of this can't be defined in parse time of the code.

**Comment by TheLimeGlass** [comment]
This was fixed in the 1.13 edit of Skript (basically next update) this whole class got re-written.

**Comment by TheBentoBox** [comment]
I want to note that this still isn't addressed and it's pretty annoying. `set {_test} to minecraft name of target block` gives an error and it really shouldn't. If it's truly impossible to work around then this should be closed but this is a frustrating issue for anyone who works with vanilla IDs in their scripts at all (speaking as someone who does so).

**Comment by Snow-Pyon** [comment]
This is sadly unfixable since we can't define the amount of aliases an item type contains at parse-time, meaning we can't define whether this expression will be just a single object.

That said, I'm closing the issue.
