### ISSUE TITLE
Remaining alias bug & issues

### ISSUE THREAD

**Issue by TheBentoBox** [SkriptLang/Skript#1533]
1. The third alpha build is looking really solid and we're close as far as aliases are concerned. I'm not seeing materials being returned in place of the aliases anywhere anymore. However, there's still one bug remaining that I can see: blocks are still failing comparisons in particular circumstances similar to the previous ones. Hard to describe so here's a few pictures of failed comparisons:
![image](https://user-images.githubusercontent.com/6902229/45329157-082b2080-b52d-11e8-9bbf-2f0fc096f4c5.png)
![image](https://user-images.githubusercontent.com/6902229/45329158-0a8d7a80-b52d-11e8-9f75-0de4138313eb.png)
![image](https://user-images.githubusercontent.com/6902229/45329160-0c573e00-b52d-11e8-98e8-53924edb991c.png)

Most of them pass comparisons with the entire exact block state or with just the material, but there are some false failures. In the bed and wall sign examples, they fail comparisons where I omit states even though the ones I specified are correct. Perhaps there's somewhere else (in some comparison code or something?...) where we need to do `.matches()`?

The example with the leaves is more interesting: I'm specifying the exact correct block state, but it fails. My initial theory is that this is because we're not supporting the `distance` state for leaves, so it's perhaps trying to match that state (which could again be a place where we need to swap to `.matches()`). I'll note I'm **not** seeing failed comparisons for some other blocks with states we don't support (cake, cauldron, cactus, vine). The difference between leaves and those blocks is that we don't support ANY of their states (and they mostly only have one anyway) so it's just in essence a material comparison. So the tl;dr is if a block has multiple states and we don't support one

2. Sending a held item returns the default state of that item, e.g. holding an oak log and sending it will send something like `vertical oak wood log`. I'm not really sure how we'd handle this but it doesn't really make sense for held items to items to use a block state at all when they're not placed in the world.

**Comment by bensku** [comment]
I think I fixed everything you listed here, but I'm not closing this until someone confirms that everything does work.

**Comment by TheBentoBox** [comment]
I tried to freshly build the repo from master and for me only the leaves were fixed; the bed and sign comparisons still fail unless I specify direction as part of the alias, after which they work as expected, even a simple test like comparing a white bed against `white bed` fails. Held items are also now straight up returning as their material name without an alias.

Honestly the comparison stuff is fairly minor. They should still be improved later but it's not a huge deal if edge case specific detailed variations don't compare perfectly. I do think held items should be properly fixed so they just return the material alias without the added text of any block data variations, and comparisons against the basic material where you specify no block states should always pass; once both of those are working I think alias-wise this is good enough for now.

**Comment by bensku** [comment]
Hmm, so it seems I managed to break everything on my second commit. Too bad that I cannot just discard it, because it fixes very real problems.

**Comment by bensku** [comment]
Surprisingly enough, I cannot reproduce any of these issues. Are you sure you have both latest aliases and Skript running? Also, do you have latest 1.13.1 Spigot or Paper?

**Comment by TheBentoBox** [comment]
I thought I did but I must not have if it’s working for you. I’ll give it a go again soon and make sure I’m using a freshly built Spigot and such!

**Comment by TheBentoBox** [comment]
Ok, tested again and made sure I was on a totally fresh 1.13.1 build this time (not sure what I was using yesterday but it may have been 1.13.0 by accident). The "bad news" (VERY minor) is that I did still have to manually copy the aliases into the `aliases-english` folder in the built JAR since all it initially had was `test.sk`. It didn't work properly without doing that myself even though I'd expect it to be part of the build.

But the very good news: yes, it's all working now! It must have just been my version or some out-of-date aliases (or both), so my mistake there. I'm noticing a few missing aliases and things that could be updated (especially now that we basically require 1.13.1 it seems) and I'll get to doing those now/soon. But **everything** I tested that had aliases defined properly seemed to work perfectly, including blocks with many states like trapdoors. 

For posterity, here's me performing the same checks as in the top post:

![image](https://user-images.githubusercontent.com/6902229/45590491-3f237c80-b907-11e8-8d21-fd5bba759818.png)
![image](https://user-images.githubusercontent.com/6902229/45590493-4480c700-b907-11e8-9ba0-51ca87480781.png)
![image](https://user-images.githubusercontent.com/6902229/45590494-48144e00-b907-11e8-8d68-b5eb346d7a57.png)
