### ISSUE TITLE
Skript 2.4-alpha4 crashes server on start-up

### ISSUE THREAD

**Issue by SlimeDog** [SkriptLang/Skript#2203]
### Description
See title.

### Steps to Reproduce
- Update from Skript 2.4-alpha3 to Skript 2.4-alpha4
- Start server.
- Observe crash.

### Errors / Screenshots
```
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! [Skript] Severe Error:
[11:48:49] [Server thread/ERROR]: #!#! Version supports setTamed but MethodHandle lookup failed
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
[11:48:49] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:48:49] [Server thread/ERROR]: #!#! You should report it at https://github.com/SkriptLang/Skript/issues. Please copy paste this report there (or use paste service).
[11:48:49] [Server thread/ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Stack trace:
[11:48:49] [Server thread/ERROR]: #!#! java.lang.IllegalAccessException: no private access for invokespecial: interface org.bukkit.entity.Ocelot, from public Lookup
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.invoke.MethodHandles$Lookup.checkSpecialCaller(MethodHandles.java:2240)
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:1393)
[11:48:49] [Server thread/ERROR]: #!#!     at ch.njol.skript.entity.OcelotData.<clinit>(OcelotData.java:46)
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:398)
[11:48:49] [Server thread/ERROR]: #!#!     at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:108)
[11:48:49] [Server thread/ERROR]: #!#!     at ch.njol.skript.Skript.onEnable(Skript.java:426)
[11:48:49] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[11:48:49] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[11:48:49] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[11:48:49] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[11:48:49] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[11:48:49] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[11:48:49] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[11:48:49] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[11:48:49] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[11:48:49] [Server thread/ERROR]: #!#!     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[11:48:49] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:834)
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Version Information:
[11:48:49] [Server thread/ERROR]: #!#!   Skript: 2.4-alpha4
[11:48:49] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
[11:48:49] [Server thread/ERROR]: #!#!     Date: 2019-06-27
[11:48:49] [Server thread/ERROR]: #!#!   Bukkit: 1.13.2-R0.1-SNAPSHOT
[11:48:49] [Server thread/ERROR]: #!#!   Minecraft: 1.13.2
[11:48:49] [Server thread/ERROR]: #!#!   Java: 11.0.3 (Java HotSpot(TM) 64-Bit Server VM 11.0.3+12-LTS)
[11:48:49] [Server thread/ERROR]: #!#!   OS: Linux amd64 3.10.0-957.12.2.el7.x86_64
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Server platform: Spigot
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Current node: null
[11:48:49] [Server thread/ERROR]: #!#! Current item: null
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Thread: Server thread
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! Language: english
[11:48:49] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
[11:48:49] [Server thread/ERROR]: #!#! 
[11:48:49] [Server thread/ERROR]: #!#! End of Error.
[11:48:49] [Server thread/ERROR]: #!#! 
```

### Server Information
Spigot 1.13.2 final
or
Spigot 1.14.3 git-Spigot-595711b-e8b39d4 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

Skript 2.4-alpha4

Skript 2.4-alpha3 performed correctly on both platforms.

**Comment by iOshawott** [comment]
Sorry, I though that issue format is useless since all the info is in error :v And it's kinda important so I wanted to paste it faster.

**Comment by TheBentoBox** [comment]
No worries, it's not a problem, just figured since both were already posted by the time I saw them that I'd go with the one with the format.

**Comment by FranKusmiruk** [comment]
Should be fixed now, you just have to re-download the jar from the releases page. Sorry for the troubles.

**Comment by SlimeDog** [comment]
I still see 2.4-alpha4 as the last release. Surely the same version string wasn't reused.

**Comment by ShaneBeee** [comment]
> I still see 2.4-alpha4 as the last release. Surely the same version string wasn't reused.

It is, he just updated the downloadable jar file rather than creating a new release for a small fix

**Comment by SlimeDog** [comment]
Thanks for the clarification. Bad practice, although in this case it will be reasonably clear which 2.4-alpha4 I have, since the first one fails on start-up.

**Comment by SlimeDog** [comment]
Verified that the second 2.4-alpha4 loads successfully, and seems to handle cats correctly on Spigot 1.14.3 (and Spigot 1.13.2 final).
