### ISSUE TITLE
Memory Leak in Function

### ISSUE THREAD

**Issue by Wealthyturtle** [SkriptLang/Skript#2337]
### Description

When a function returns a variable, and the function is called but does not actually get stored in a variable (local or global), it causes a leak

### Steps to Reproduce

```
function lore_add(i: item, s: string) :: item:
    set line (size of {_i}'s lore)+1 of {_i}'s lore to {_s}
    print_lore({_i})
    return {_i}

function print_lore(i: item):
    set {_lore::*} to {_i}'s lore
    set {_c} to 1
    loop {_lore::*}:
        broadcast "L%{_c}%: %loop-value%"
        increase {_c} by 1

command /test:
    trigger:
        lore_add(dirt, "This should only appear once")
```

If you run the ```/test``` command **multiple times,** this occurs:
![image](https://user-images.githubusercontent.com/19924575/62467025-64420780-b7c5-11e9-99c8-dc32140b0fdc.png)
As you can see, at the first call of /test there's only 1 line of lore, but then the next call of /test has 2, followed by 3, ...

### Expected Behavior

Prior lore should not be stored, since it's technically local

### Server Information
* **Server version/platform:**       Spigot 1.14.4
* **Skript version:**                Skript 2.4-beta5

### Additional Context
Should probably test other vectors other than lore, to confirm if it's limited to lore or all expressions

Also, @bensku

**Comment by bensku** [comment]
Since when does this occur?

**Comment by Wealthyturtle** [comment]
Can test other versions of Skript, give me a moment

**Comment by Wealthyturtle** [comment]
Skript 2.4-alpha1: Exists
Still testing other Skript versions

**Comment by Wealthyturtle** [comment]
@bensku Seems like Skript 2.2-dev34 broke it, try starting from there?

**Comment by bensku** [comment]
Thanks for investigating it! dev34 is so old that I'm probably not going to investigate there. Rewriting messy parts of the function system is likely faster, and produces other benefits (readable code) too.

Unfortunately this means that the fix will take a while.

**Comment by TheLimeGlass** [comment]
Potentially related https://github.com/SkriptLang/Skript/issues/2279

**Comment by bensku** [comment]
Likely fixed in #2383. In the end, this was not terribly hard to fix.

**Comment by Wealthyturtle** [comment]
I just found out that this issue has been reintroduced in some recent Skript update, as this memory leak still occurs in Skript 2.5-alpha3.

**Comment by Wealthyturtle** [comment]
Just to note, it seems like the memory leak was never resolved by the function overhaul. See #2877 for some memory profiles taken that show the leak.

**Comment by Govindass** [comment]
still present in Skript 2.5.1 & 1.16.4

**Comment by TPGamesNL** [comment]
The lore part of this issue is caused by #3779 (see the comment for example with items)
The loop memory leak (#2877) is caused by [`Loop#current`](https://github.com/SkriptLang/Skript/blob/45b348e47005626d1e5808d589e634b368c1ff5f/src/main/java/ch/njol/skript/lang/Loop.java#L44) not being removed from:
![image](https://user-images.githubusercontent.com/29547183/112756723-cda00b00-8fe6-11eb-8128-510aeb8f8845.png)
(it might also be [`Loop#currentIter`](https://github.com/SkriptLang/Skript/blob/45b348e47005626d1e5808d589e634b368c1ff5f/src/main/java/ch/njol/skript/lang/Loop.java#L45), but that field at least has `remove` called somewhere, so it's more likely to be `Loop#current`)

**Comment by Govindass** [comment]
thank you so much for putting effort into this
