### ISSUE TITLE
Item name is overlooked

### ISSUE THREAD

**Issue by MisterPawlak** [SkriptLang/Skript#2821]
Please script to remove an item with a specific name, and it will simply delete the item.

https://youtu.be/7UD6lSInmmQ

```vb
command /changename [<text>]:
    trigger:
        if player has 1 paper named "&6&lNameChanger":
            if player's tool is carved pumpkin or bedrock or sponge or paper or turtle egg or enchanted book or seed or gold nugget:
                send "&cYou dont have permission do this!"
            else:
                remove 1 paper with name "&6&lNameChanger" from player
                set the name of player's tool to coloured argument
        else:
            send "&cYou dont have a NameChanger!" to player
```

### Server Information
* **Server version/platform: git-Paper-98 (MC: 1.15.2), Ubuntu 18.04
* **Skript version: 2.4.1

**Comment by ShaneBeee** [comment]
Can you please test this on 2.5alpha1 ... I think this may have been fixed already.

**Comment by iOshawott** [comment]
My god! We talk in other issues that it is not fixed :(  #2756 and #2714 , I'm waiting 19 days for response. And please give a priority to #2802 if possible...

**Comment by ShaneBeee** [comment]
Duplicate of #2714
